### ISSUE TITLE
Create Zenith.js - A Minimalist Code Display Library

### ISSUE THREAD

**Issue by caelok** [caelok/caelok.github.io#3]
Create a single-file JavaScript library called Zenith.js for displaying and styling code snippets with the following features:

## Core Features
- Syntax highlighting for multiple programming languages
- Customizable color themes
- Code block styling with modern design
- API integration capabilities
- Font customization
- Copy code button
- Line numbers
- Responsive design

### Base HTML Structure
```html
<!DOCTYPE html>
<html>
<head>
    <title>Zenith.js Demo</title>
    <script src="zenith.js"></script>
    <link rel="stylesheet" href="zenith.css">
</head>
<body>
    <div class="zenith-container">
        <pre><code class="language-javascript">
            // Your code here
        </code></pre>
    </div>
</body>
</html>
```

### Library Implementation (zenith.js)
```javascript
class Zenith {
    constructor(options = {}) {
        this.options = {
            theme: options.theme || 'default',
            fontSize: options.fontSize || '14px',
            lineNumbers: options.lineNumbers !== undefined ? options.lineNumbers : true,
            copyButton: options.copyButton !== undefined ? options.copyButton : true,
            font: options.font || 'JetBrains Mono, monospace',
        };
        this.init();
    }

    init() {
        // Initialize syntax highlighting
        // Add copy button functionality
        // Add line numbers
        // Apply theme
    }

    static themes = {
        default: {
            background: '#282c34',
            text: '#abb2bf',
            comment: '#5c6370',
            keyword: '#c678dd',
            string: '#98c379',
            number: '#d19a66',
            function: '#61afef',
        },
        light: {
            background: '#ffffff',
            text: '#383a42',
            comment: '#a0a1a7',
            keyword: '#a626a4',
            string: '#50a14f',
            number: '#986801',
            function: '#4078f2',
        }
    };
}
```

### CSS Implementation (zenith.css)
```css
.zenith-container {
    background: var(--zenith-bg, #282c34);
    border-radius: 8px;
    padding: 1em;
    margin: 1em 0;
    position: relative;
    font-family: var(--zenith-font, 'JetBrains Mono', monospace);
}

.zenith-container pre {
    margin: 0;
    padding: 0;
    overflow-x: auto;
}

.zenith-container code {
    font-size: var(--zenith-font-size, 14px);
    line-height: 1.5;
}

.zenith-line-numbers {
    position: absolute;
    left: 0;
    top: 0;
    padding: 1em 0.5em;
    border-right: 1px solid rgba(255,255,255,0.1);
    color: rgba(255,255,255,0.3);
    user-select: none;
}

.zenith-copy-button {
    position: absolute;
    right: 0.5em;
    top: 0.5em;
    background: rgba(255,255,255,0.1);
    border: none;
    border-radius: 4px;
    color: #fff;
    padding: 0.5em 1em;
    cursor: pointer;
    transition: background 0.2s;
}

.zenith-copy-button:hover {
    background: rgba(255,255,255,0.2);
}
```

## API Documentation
```javascript
// Initialize Zenith
const zenith = new Zenith({
    theme: 'default',
    fontSize: '14px',
    lineNumbers: true,
    copyButton: true,
    font: 'JetBrains Mono, monospace'
});

// Apply to specific elements
zenith.apply('.my-code-block');

// Change theme
zenith.setTheme('light');

// Custom theme
zenith.addTheme('custom', {
    background: '#1a1a1a',
    text: '#ffffff',
    // ... other color definitions
});
```

## Development Tasks
1. Create base library structure
2. Implement syntax highlighting engine
3. Add theme system
4. Add copy button functionality
5. Implement line numbers
6. Add customization API
7. Create documentation
8. Add example implementations
9. Test cross-browser compatibility

## Testing Requirements
- Test in latest versions of Chrome, Firefox, Safari, and Edge
- Test responsiveness on mobile devices
- Test syntax highlighting for popular languages
- Test theme switching
- Test copy functionality
- Test with different fonts and sizes

## Documentation Requirements
- Installation guide
- Basic usage examples
- API reference
- Theme customization guide
- Advanced usage examples
